# Generated by Django 4.2 on 2023-04-15 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, verbose_name='shortcut')),
                ('efforts', models.DurationField()),
                ('status', models.CharField(choices=[('1', 'Stuck'), ('2', 'Working'), ('3', 'Done')], default=1, max_length=7)),
                ('complete_per', models.FloatField(default=0, max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('upd_date', models.DateField(auto_now=True)),
                ('dead_line', models.DateField()),
                ('github', models.URLField(blank=True)),
                ('product_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, verbose_name='shortcut')),
                ('dead_line', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('1', 'Stuck'), ('2', 'Working'), ('3', 'Done')], default=1, max_length=7)),
                ('due', models.CharField(choices=[('1', 'On Due'), ('2', 'Overdue'), ('3', 'Done')], default=1, max_length=7)),
            ],
            options={
                'ordering': ['project', 'task_name'],
            },
        ),
    ]
