# Generated by Django 4.2 on 2023-04-15 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assign',
            field=models.ManyToManyField(to='register.member'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(related_name='developing_project', to='register.member'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(related_name='managing_project', to='register.member'),
        ),
        migrations.AddField(
            model_name='project',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
