# Generated by Django 4.2 on 2023-04-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
