# Generated by Django 4.2 on 2023-04-15 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_projectrequest_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_project_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
