# Generated by Django 4.2 on 2023-04-15 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_projectrequest_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_project_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
