# Generated by Django 4.2 on 2023-04-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectrequest_requester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager',
            new_name='managers',
        ),
    ]
